{{- if .Values.secrets.createExample -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.existingSecret }}
  labels:
    {{- include "limes-axis.labels" . | nindent 4 }}
  annotations:
    limes-axis.io/purpose: example-only
type: Opaque
stringData:
  AXIS_POSTGRES_DSN: {{ .Values.secrets.exampleData.AXIS_POSTGRES_DSN | quote }}
  AXIS_TYPEDB_USERNAME: {{ .Values.secrets.exampleData.AXIS_TYPEDB_USERNAME | quote }}
  AXIS_TYPEDB_PASSWORD: {{ .Values.secrets.exampleData.AXIS_TYPEDB_PASSWORD | quote }}
  AXIS_AUDIT_LEDGER_SIGNING_SECRET: {{ .Values.secrets.exampleData.AXIS_AUDIT_LEDGER_SIGNING_SECRET | quote }}
  AXIS_OIDC_CLIENT_SECRET: {{ .Values.secrets.exampleData.AXIS_OIDC_CLIENT_SECRET | quote }}
  AXIS_OIDC_SESSION_COOKIE_SIGNING_SECRET: {{ .Values.secrets.exampleData.AXIS_OIDC_SESSION_COOKIE_SIGNING_SECRET | quote }}
  AXIS_CONNECTOR_EXPORT_S3_ACCESS_KEY: {{ .Values.secrets.exampleData.AXIS_CONNECTOR_EXPORT_S3_ACCESS_KEY | quote }}
  AXIS_CONNECTOR_EXPORT_S3_SECRET_KEY: {{ .Values.secrets.exampleData.AXIS_CONNECTOR_EXPORT_S3_SECRET_KEY | quote }}
{{- end }}
