apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "limes-axis.fullname" . }}-web
  labels:
    {{- include "limes-axis.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "limes-axis.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "limes-axis.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
      {{- with .Values.web.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "limes-axis.serviceAccountName" . }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.web.podSecurityContext | nindent 8 }}
      containers:
        - name: web
          image: {{ include "limes-axis.webImage" . | quote }}
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: NEXT_PUBLIC_AXIS_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "limes-axis.fullname" . }}-config
                  key: NEXT_PUBLIC_AXIS_API_BASE_URL
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.web.securityContext | nindent 12 }}
