from __future__ import annotations

import argparse
import re
import tomllib
from datetime import date
from pathlib import Path
from typing import Any

ALLOWED_DISPOSITIONS = {
    "oss",
    "hosted",
    "enterprise-private-cloud",
    "shared-sdk",
    "undecided",
}
ALLOWED_LIFECYCLES = {"current", "planned"}
REQUIRED_AREAS = {
    "apps/web",
    "services/api",
    "services/worker",
    "packages/schemas",
    "packages/sdk-python",
    "infra/docker",
    "infra/helm/limes-axis",
}
DISPOSITION_LABELS = {
    "oss": "OSS candidate",
    "hosted": "Hosted",
    "enterprise-private-cloud": "Enterprise / private cloud",
    "shared-sdk": "Shared SDK",
    "undecided": "Undecided",
}


def load_matrix(path: Path) -> dict[str, Any]:
    with path.open("rb") as matrix_file:
        return tomllib.load(matrix_file)


def validate_matrix(matrix: dict[str, Any], repo_root: Path) -> list[str]:
    errors: list[str] = []
    if matrix.get("schema_version") != 1:
        errors.append("schema_version must be 1")
    for field in ("last_reviewed", "decision_owner", "topology_adr"):
        if not isinstance(matrix.get(field), str) or not matrix[field].strip():
            errors.append(f"{field} must be a non-empty string")
    try:
        date.fromisoformat(matrix.get("last_reviewed", ""))
    except (TypeError, ValueError):
        errors.append("last_reviewed must use YYYY-MM-DD")
    topology_adr = matrix.get("topology_adr")
    if isinstance(topology_adr, str):
        topology_path = (repo_root / topology_adr).resolve()
        if not topology_path.is_relative_to(repo_root) or not topology_path.is_file():
            errors.append("topology_adr must resolve to a repository file")

    capabilities = matrix.get("capabilities")
    if not isinstance(capabilities, list) or not capabilities:
        return [*errors, "capabilities must be a non-empty array"]

    seen_ids: set[str] = set()
    covered_areas: set[str] = set()
    for index, capability in enumerate(capabilities, start=1):
        prefix = f"capabilities[{index}]"
        if not isinstance(capability, dict):
            errors.append(f"{prefix} must be a table")
            continue

        capability_id = capability.get("id")
        if not isinstance(capability_id, str) or not capability_id.strip():
            errors.append(f"{prefix}.id must be a non-empty string")
        elif re.fullmatch(r"[A-Z0-9]+(?:-[A-Z0-9]+)*", capability_id) is None:
            errors.append(f"{prefix}.id must use upper kebab case: {capability_id}")
        elif capability_id in seen_ids:
            errors.append(f"duplicate capability id: {capability_id}")
        else:
            seen_ids.add(capability_id)

        for field in ("name", "rationale"):
            value = capability.get(field)
            if not isinstance(value, str) or not value.strip():
                errors.append(f"{prefix}.{field} must be a non-empty string")

        lifecycle = capability.get("lifecycle")
        if lifecycle not in ALLOWED_LIFECYCLES:
            errors.append(f"{prefix}.lifecycle is invalid: {lifecycle!r}")
        disposition = capability.get("disposition")
        if disposition not in ALLOWED_DISPOSITIONS:
            errors.append(f"{prefix}.disposition is invalid: {disposition!r}")

        for field in ("areas", "evidence"):
            values = capability.get(field)
            if not isinstance(values, list) or not values or not all(
                isinstance(value, str) and value.strip() for value in values
            ):
                errors.append(f"{prefix}.{field} must be a non-empty string array")
                continue
            if field == "areas":
                covered_areas.update(values)
            for value in values:
                target = (repo_root / value.split("#", 1)[0]).resolve()
                if not target.is_relative_to(repo_root) or not target.exists():
                    errors.append(f"{prefix}.{field} path does not exist: {value}")

    for area in sorted(REQUIRED_AREAS - covered_areas):
        errors.append(f"repository area is not inventoried: {area}")
    return errors


def export_blockers(matrix: dict[str, Any]) -> list[str]:
    return [
        capability["id"]
        for capability in matrix.get("capabilities", [])
        if capability.get("disposition") == "undecided"
    ]


def _link(path: str) -> str:
    target, separator, anchor = path.partition("#")
    suffix = f"#{anchor}" if separator else ""
    return f"[`{path}`](../{target}{suffix})"


def render_matrix(matrix: dict[str, Any]) -> str:
    lines = [
        "# Axis Edition Capability Matrix",
        "",
        "<!-- Generated by scripts/check_edition_matrix.py; edit "
        "docs/edition-capabilities.toml. -->",
        "",
        f"- **Schema:** {matrix['schema_version']}",
        f"- **Last reviewed:** {matrix['last_reviewed']}",
        f"- **Decision owner:** `{matrix['decision_owner']}`",
        "",
        "This generated inventory records product disposition, not current file",
        "visibility. Every listed area still lives in the private commercial source",
        "repository. See [the edition rules](./editions.md).",
        "",
        "| ID | Capability | Lifecycle | Disposition | Current/planned areas | "
        "Evidence | Rationale |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for capability in matrix["capabilities"]:
        areas = "<br>".join(f"`{area}`" for area in capability["areas"])
        evidence = "<br>".join(_link(path) for path in capability["evidence"])
        rationale = capability["rationale"].replace("|", "\\|")
        lines.append(
            (
                "| {id} | {name} | {lifecycle} | {disposition} | {areas} | "
                "{evidence} | {rationale} |"
            ).format(
                id=capability["id"],
                name=capability["name"],
                lifecycle=capability["lifecycle"].title(),
                disposition=DISPOSITION_LABELS[capability["disposition"]],
                areas=areas,
                evidence=evidence,
                rationale=rationale,
            )
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate the Axis edition matrix.")
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--write", action="store_true", help="Regenerate the Markdown inventory.")
    parser.add_argument(
        "--require-export-ready",
        action="store_true",
        help="Fail when any capability disposition is undecided.",
    )
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    matrix_path = repo_root / "docs/edition-capabilities.toml"
    generated_path = repo_root / "docs/editions-matrix.md"
    matrix = load_matrix(matrix_path)
    errors = validate_matrix(matrix, repo_root)
    if errors:
        for error in errors:
            print(f"edition matrix: {error}")
        return 1

    rendered = render_matrix(matrix)
    if args.write:
        generated_path.write_text(rendered, encoding="utf-8")
    elif not generated_path.exists() or generated_path.read_text(encoding="utf-8") != rendered:
        print("edition matrix: docs/editions-matrix.md is stale; run with --write")
        return 1

    blockers = export_blockers(matrix)
    if args.require_export_ready and blockers:
        print("edition export blocked by undecided capabilities: " + ", ".join(blockers))
        return 1

    print(
        f"Edition matrix OK ({len(matrix['capabilities'])} capabilities, "
        f"{len(blockers)} undecided)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
