"""audit explorer reference record

Revision ID: 0028_audit_explorer_reference
Revises: 0027_approval_inbox_reference
Create Date: 2026-06-22
"""

from collections.abc import Sequence
from datetime import UTC, datetime
from uuid import uuid4

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0028_audit_explorer_reference"
down_revision: str | None = "0027_approval_inbox_reference"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

AUDIT_EXPLORER_PAYLOAD = {
    "tenant_id": "tenant_demo_manufacturing",
    "plant_name": "Ravenna Works",
    "scenario": "Plant Operations Cockpit",
    "as_of": "2026-06-21T16:30:00+02:00",
    "ledger_status": "watch",
    "metrics": [
        {
            "label": "Audit Events",
            "value": "9",
            "detail": "Synthetic public-safe events for the manufacturing demo",
            "status": "ready",
        },
        {
            "label": "Action Gates",
            "value": "3",
            "detail": "Approval and workflow signal events are visible",
            "status": "action_required",
        },
        {
            "label": "Policy Blocks",
            "value": "1",
            "detail": "External model egress block is recorded",
            "status": "ready",
        },
        {
            "label": "Replay",
            "value": "Preview",
            "detail": "Events are shaped for the replay simulation console",
            "status": "watch",
        },
    ],
    "filter_options": {
        "tenants": ["tenant_demo_manufacturing"],
        "event_types": [
            "agent.proposal.created",
            "ontology.relationship.read",
            "permission.check.evaluated",
            "policy.egress.blocked",
            "workflow.signal.awaiting",
            "workflow.started",
        ],
        "scopes": [
            "agent_quality_risk",
            "approvals:supply:decide",
            "asset_line_2_packaging",
            "wf_maintenance_reschedule",
            "wf_quality_hold_review",
            "wf_supplier_delay_review",
        ],
        "actors": [
            "axis-permission-engine",
            "axis-temporal-adapter",
            "maintenance-planner-agent",
            "model-router",
            "plant-operations-owner-role",
            "quality-risk-agent",
            "supply-risk-agent",
            "workflow-runtime",
        ],
        "categories": ["agent", "ontology", "permission", "policy", "workflow"],
    },
    "events": [
        {
            "audit_event_id": "audit_20260621_140500_workflow_started",
            "occurred_at": "2026-06-21T14:05:00+02:00",
            "tenant_id": "tenant_demo_manufacturing",
            "actor_id": "workflow-runtime",
            "actor_type": "service",
            "event_type": "workflow.started",
            "category": "workflow",
            "domain": "Supply",
            "scope": "wf_supplier_delay_review",
            "result": "started",
            "severity": "ready",
            "source": "Temporal",
            "summary": "Supplier delay workflow created from the supply risk signal.",
            "permission_scope": "workflows:read",
            "data_classification": "public-demo",
            "related_workflow_id": "wf_supplier_delay_review",
            "related_approval_id": None,
            "related_agent_id": None,
            "evidence_refs": ["risk_supplier_delay", "asset_motors_batch"],
            "payload_preview": {
                "workflow_id": "wf_supplier_delay_review",
                "runtime": "Temporal OSS",
                "adapter": "axis-temporal-adapter",
            },
        },
        {
            "audit_event_id": "audit_20260621_141200_agent_proposal",
            "occurred_at": "2026-06-21T14:12:00+02:00",
            "tenant_id": "tenant_demo_manufacturing",
            "actor_id": "supply-risk-agent",
            "actor_type": "agent",
            "event_type": "agent.proposal.created",
            "category": "agent",
            "domain": "Supply",
            "scope": "wf_supplier_delay_review",
            "result": "approval_required",
            "severity": "action_required",
            "source": "Axis",
            "summary": "L2 agent drafted an expedite supplier batch action payload.",
            "permission_scope": "agents:read",
            "data_classification": "public-demo",
            "related_workflow_id": "wf_supplier_delay_review",
            "related_approval_id": "appr_expedite_supplier_batch",
            "related_agent_id": "agent_supply_risk",
            "evidence_refs": ["appr_expedite_supplier_batch", "asset_line_2_packaging"],
            "payload_preview": {
                "action": "Expedite supplier batch",
                "autonomy_level": "L2",
                "risk_level": "high",
            },
        },
        {
            "audit_event_id": "audit_20260621_141800_signal_awaiting",
            "occurred_at": "2026-06-21T14:18:00+02:00",
            "tenant_id": "tenant_demo_manufacturing",
            "actor_id": "axis-temporal-adapter",
            "actor_type": "service",
            "event_type": "workflow.signal.awaiting",
            "category": "workflow",
            "domain": "Supply",
            "scope": "wf_supplier_delay_review",
            "result": "waiting_for_approval",
            "severity": "action_required",
            "source": "Axis Workflow Runtime",
            "summary": "Workflow paused at the human approval gate.",
            "permission_scope": "workflows:read",
            "data_classification": "public-demo",
            "related_workflow_id": "wf_supplier_delay_review",
            "related_approval_id": "appr_expedite_supplier_batch",
            "related_agent_id": None,
            "evidence_refs": ["appr_expedite_supplier_batch"],
            "payload_preview": {
                "signal": "approval.decision",
                "required_role": "plant-operations-owner",
                "status": "waiting",
            },
        },
        {
            "audit_event_id": "audit_20260621_133900_egress_blocked",
            "occurred_at": "2026-06-21T13:39:00+02:00",
            "tenant_id": "tenant_demo_manufacturing",
            "actor_id": "model-router",
            "actor_type": "service",
            "event_type": "policy.egress.blocked",
            "category": "policy",
            "domain": "Security",
            "scope": "agent_quality_risk",
            "result": "blocked_by_default",
            "severity": "ready",
            "source": "Axis Policy",
            "summary": "External model egress was blocked for quality evidence.",
            "permission_scope": "security:read",
            "data_classification": "public-demo",
            "related_workflow_id": None,
            "related_approval_id": None,
            "related_agent_id": "agent_quality_risk",
            "evidence_refs": ["policy_external_egress", "wf_quality_hold_review"],
            "payload_preview": {
                "model_policy": "no-external-egress",
                "provider": "external",
                "decision": "blocked",
            },
        },
        {
            "audit_event_id": "audit_20260621_134400_quality_proposal",
            "occurred_at": "2026-06-21T13:44:00+02:00",
            "tenant_id": "tenant_demo_manufacturing",
            "actor_id": "quality-risk-agent",
            "actor_type": "agent",
            "event_type": "agent.proposal.created",
            "category": "agent",
            "domain": "Quality",
            "scope": "wf_quality_hold_review",
            "result": "review_required",
            "severity": "watch",
            "source": "Axis",
            "summary": "L2 agent drafted a quality hold proposal for Batch Q-1842.",
            "permission_scope": "agents:read",
            "data_classification": "public-demo",
            "related_workflow_id": "wf_quality_hold_review",
            "related_approval_id": "appr_quality_hold_batch",
            "related_agent_id": "agent_quality_risk",
            "evidence_refs": ["risk_quality_drift", "asset_batch_q_1842"],
            "payload_preview": {
                "action": "Place Batch Q-1842 on quality hold",
                "autonomy_level": "L2",
                "risk_level": "high",
            },
        },
        {
            "audit_event_id": "audit_20260621_151800_maintenance_proposal",
            "occurred_at": "2026-06-21T15:18:00+02:00",
            "tenant_id": "tenant_demo_manufacturing",
            "actor_id": "maintenance-planner-agent",
            "actor_type": "agent",
            "event_type": "agent.proposal.created",
            "category": "agent",
            "domain": "Maintenance",
            "scope": "wf_maintenance_reschedule",
            "result": "proposal_ready",
            "severity": "watch",
            "source": "Axis",
            "summary": "L2 agent drafted the Press 4 maintenance schedule shift proposal.",
            "permission_scope": "agents:read",
            "data_classification": "public-demo",
            "related_workflow_id": "wf_maintenance_reschedule",
            "related_approval_id": "appr_shift_maintenance_window",
            "related_agent_id": None,
            "evidence_refs": ["risk_maintenance_window", "asset_press_4"],
            "payload_preview": {
                "action": "Shift Press 4 maintenance window",
                "autonomy_level": "L2",
                "risk_level": "medium",
            },
        },
        {
            "audit_event_id": "audit_20260621_152500_maintenance_signal",
            "occurred_at": "2026-06-21T15:25:00+02:00",
            "tenant_id": "tenant_demo_manufacturing",
            "actor_id": "axis-temporal-adapter",
            "actor_type": "service",
            "event_type": "workflow.signal.awaiting",
            "category": "workflow",
            "domain": "Maintenance",
            "scope": "wf_maintenance_reschedule",
            "result": "waiting_for_owner_review",
            "severity": "watch",
            "source": "Axis Workflow Runtime",
            "summary": "Workflow paused before mutating the maintenance schedule.",
            "permission_scope": "workflows:read",
            "data_classification": "public-demo",
            "related_workflow_id": "wf_maintenance_reschedule",
            "related_approval_id": "appr_shift_maintenance_window",
            "related_agent_id": None,
            "evidence_refs": ["appr_shift_maintenance_window"],
            "payload_preview": {
                "signal": "maintenance.owner.review",
                "required_role": "maintenance-owner",
                "status": "waiting",
            },
        },
        {
            "audit_event_id": "audit_20260621_153200_permission_check",
            "occurred_at": "2026-06-21T15:32:00+02:00",
            "tenant_id": "tenant_demo_manufacturing",
            "actor_id": "axis-permission-engine",
            "actor_type": "service",
            "event_type": "permission.check.evaluated",
            "category": "permission",
            "domain": "Supply",
            "scope": "approvals:supply:decide",
            "result": "allowed_for_owner_role",
            "severity": "ready",
            "source": "Axis Permissions",
            "summary": "Supply approval decision permission evaluated for the owner role.",
            "permission_scope": "permissions:read",
            "data_classification": "public-demo",
            "related_workflow_id": None,
            "related_approval_id": "appr_expedite_supplier_batch",
            "related_agent_id": None,
            "evidence_refs": ["plant-operations-owner", "appr_expedite_supplier_batch"],
            "payload_preview": {
                "role": "plant-operations-owner",
                "permission": "approvals:supply:decide",
                "decision": "allowed",
            },
        },
        {
            "audit_event_id": "audit_20260621_154000_ontology_read",
            "occurred_at": "2026-06-21T15:40:00+02:00",
            "tenant_id": "tenant_demo_manufacturing",
            "actor_id": "plant-operations-owner-role",
            "actor_type": "role",
            "event_type": "ontology.relationship.read",
            "category": "ontology",
            "domain": "Operations",
            "scope": "asset_line_2_packaging",
            "result": "allowed",
            "severity": "ready",
            "source": "TypeDB Boundary",
            "summary": "Operations owner inspected supplier delay relationships for Line 2.",
            "permission_scope": "operations:read",
            "data_classification": "public-demo",
            "related_workflow_id": "wf_supplier_delay_review",
            "related_approval_id": None,
            "related_agent_id": None,
            "evidence_refs": ["asset_line_2_packaging", "risk_supplier_delay"],
            "payload_preview": {
                "node": "asset_line_2_packaging",
                "relation": "impacts",
                "decision": "allowed",
            },
        },
    ],
    "retention_notes": [
        "This public audit explorer reference is read-only and synthetic.",
        "Payload previews are redacted and contain no customer data or credentials.",
        "Production audit events must be append-only and tenant-scoped.",
        "Export, retention policy enforcement and replay remain Platform work.",
    ],
}


def upgrade() -> None:
    reference_table = sa.table(
        "demo_reference_records",
        sa.column("id", postgresql.UUID(as_uuid=True)),
        sa.column("tenant_id", sa.String(length=80)),
        sa.column("surface", sa.String(length=120)),
        sa.column("reference_id", sa.String(length=180)),
        sa.column("status", sa.String(length=80)),
        sa.column("source", sa.String(length=120)),
        sa.column("version", sa.String(length=80)),
        sa.column("payload", postgresql.JSONB(astext_type=sa.Text())),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    now = datetime(2026, 6, 22, 0, 0, tzinfo=UTC)
    op.bulk_insert(
        reference_table,
        [
            {
                "id": uuid4(),
                "tenant_id": "tenant_demo_manufacturing",
                "surface": "audit",
                "reference_id": "manufacturing-audit-explorer",
                "status": "active",
                "source": "bootstrap",
                "version": "2026-06-22",
                "payload": AUDIT_EXPLORER_PAYLOAD,
                "created_at": now,
                "updated_at": now,
            }
        ],
    )


def downgrade() -> None:
    op.execute(
        sa.text(
            "DELETE FROM demo_reference_records "
            "WHERE tenant_id = 'tenant_demo_manufacturing' "
            "AND surface = 'audit' "
            "AND reference_id = 'manufacturing-audit-explorer'"
        )
    )
