import type { ManufacturingApprovalInbox } from "@/lib/approval-demo";
import type { ManufacturingAuditExplorer } from "@/lib/audit-demo";
import type { ManufacturingModelRouting } from "@/lib/model-routing-demo";
import type {
  IdentitySessionReadModel,
  ManufacturingOperationsSnapshot,
  ManufacturingOverview,
} from "@/lib/platform-overview";
import type { PlatformPolicyRegistry } from "@/lib/platform-policies";

/*
 * Shared API-payload fixtures for the overview section tests. Shapes mirror
 * the live Axis API contracts in `lib/*-demo.ts` / `lib/platform-overview.ts`.
 */

export const overviewFixture: ManufacturingOverview = {
  tenant_id: "tenant_fixture",
  plant_name: "Fixture Works",
  scenario: "Plant Operations Cockpit",
  as_of: "2026-07-10T09:00:00+02:00",
  metrics: [
    {
      label: "Workflow Load",
      value: "2 active",
      detail: "1 production, 1 supplier flow",
      status: "watch",
    },
    {
      label: "Approvals",
      value: "1 pending",
      detail: "1 high-risk action requires human approval today",
      status: "action_required",
    },
    {
      label: "Agents",
      value: "2 governed",
      detail: "All agents remain within L0-L2 autonomy",
      status: "ready",
    },
    {
      label: "Audit",
      value: "128 events",
      detail: "Static seeded audit headline that must not be displayed",
      status: "ready",
    },
  ],
  risk_signals: [
    {
      title: "Supplier delay may block Line 2 packaging",
      domain: "Supply",
      severity: "action_required",
      owner_role: "plant-operations-owner",
      evidence: "supplier_status:supplier_alfa",
      related_asset: "asset_line_2_packaging",
    },
    {
      title: "Quality drift detected on Batch Q-1842",
      domain: "Quality",
      severity: "watch",
      owner_role: "quality-owner",
      evidence: "qms_deviation:batch_q_1842",
      related_asset: "asset_batch_q_1842",
    },
  ],
  workflows: [
    {
      workflow_id: "wf_supplier_delay_review",
      name: "Supplier Delay Review",
      state: "waiting_for_approval",
      owner_role: "plant-operations-owner",
      blocker: "Awaiting expedite approval",
      eta: "Today 17:30",
    },
    {
      workflow_id: "wf_quality_hold",
      name: "Quality Hold Review",
      state: "investigating",
      owner_role: "quality-owner",
      blocker: null,
      eta: "Today 18:00",
    },
  ],
  approvals: [
    {
      approval_id: "appr_fixture_expedite",
      action: "Expedite supplier batch",
      risk_level: "high",
      requested_by: "agent_supply_fixture",
      owner_role: "plant-operations-owner",
      due: "Today 17:30",
    },
  ],
  agents: [
    {
      agent_id: "agent_supply_fixture",
      name: "Supply Risk Agent",
      autonomy_level: "L2",
      status: "waiting_for_approval",
      proposals_pending: 1,
      model_policy: "no_external_egress",
    },
    {
      agent_id: "agent_quality_fixture",
      name: "Quality Risk Agent",
      autonomy_level: "L1",
      status: "drafting_actions",
      proposals_pending: 0,
      model_policy: "local_or_approved_provider",
    },
  ],
  audit_events: [
    {
      event: "approval.decision.recorded",
      actor: "plant-operations-owner",
      scope: "wf_supplier_delay_review",
      result: "approve",
    },
  ],
};

export const snapshotFixture: ManufacturingOperationsSnapshot = {
  tenant_id: "tenant_fixture",
  plant_name: "Fixture Works",
  scenario: "Plant Operations Cockpit",
  as_of: "2026-07-10T10:30:00+02:00",
  metrics: [
    {
      label: "Operation Records",
      value: "6",
      detail: "Persisted tenant-scoped operational records",
      status: "ready",
    },
    {
      label: "Open Workflows",
      value: "1",
      detail: "Persisted workflows that are not completed",
      status: "action_required",
    },
  ],
  domain_snapshots: [
    {
      domain: "Supply",
      record_count: 2,
      action_required_count: 1,
      watch_count: 1,
      highest_risk_level: "high",
      owner_roles: ["plant-operations-owner"],
      workflow_ids: ["wf_supplier_delay_review"],
      evidence_refs: ["supplier_status:supplier_alfa"],
    },
  ],
  latest_daily_briefs: [],
  risk_scenarios: [],
  active_workflows: [
    {
      workflow_id: "wf_supplier_delay_review",
      name: "Supplier Delay Review",
      domain: "Supply",
      state: "approval_approved",
      status: "ready",
      owner_role: "plant-operations-owner",
      autonomy_level: "L2",
      blocker: null,
      pending_signal_count: 0,
      replay_ready: true,
    },
  ],
  pending_approvals: [],
  recent_audit_events: [
    {
      event_type: "connector.run_sync.checkpoints_read",
      actor_id: "connector-runtime",
      created_at: "2026-07-10T10:20:00+02:00",
      payload_refs: { connector_id: "conn_assets_csv" },
    },
    {
      event_type: "approval.decision.recorded",
      actor_id: "plant-operations-owner-role",
      created_at: "2026-07-10T10:25:00+02:00",
      payload_refs: { approval_id: "appr_fixture_expedite" },
    },
  ],
  generation_boundary: "tenant_scoped_postgres",
  notes: [],
};

export const modelRoutingFixture: ManufacturingModelRouting = {
  tenant_id: "tenant_fixture",
  plant_name: "Fixture Works",
  scenario: "Plant Operations Cockpit",
  as_of: "2026-07-10T09:00:00+02:00",
  routing_status: "watch",
  metrics: [],
  filter_options: {
    domains: ["Operations", "Supply"],
    providers: ["local-vllm"],
    model_policies: ["no-external-egress"],
    egress_decisions: ["local_allowed", "blocked_by_default"],
    statuses: ["ready", "watch"],
  },
  provider_options: [],
  routes: [
    {
      route_id: "route_daily_brief_local",
      agent_id: "agent_daily_brief",
      agent_name: "Daily Brief Agent",
      domain: "Operations",
      provider_id: "local-vllm",
      provider_name: "Local vLLM Gateway",
      model: "axis-local-brief-7b",
      model_policy: "local-or-approved-provider",
      prompt_classification: "operational-summary",
      data_boundary: "tenant-private-runtime",
      external_egress_requested: false,
      external_egress_allowed: false,
      egress_decision: "local_allowed",
      decision_reason: "Local provider satisfies the tenant model policy.",
      route_status: "ready",
      input_tokens: 1860,
      output_tokens: 420,
      estimated_cost_eur: 0.18,
      latency_ms: 840,
      cost_center: "plant-operations",
      required_permissions: ["agents:read"],
      evidence_refs: [],
      audit_event_id: "33333333-3333-4333-8333-333333333333",
      observability_events: [],
    },
    {
      route_id: "route_external_blocked",
      agent_id: "agent_supply_fixture",
      agent_name: "Supply Risk Agent",
      domain: "Supply",
      provider_id: "external-general-llm",
      provider_name: "External General LLM",
      model: "external-large",
      model_policy: "no-external-egress",
      prompt_classification: "supplier-negotiation",
      data_boundary: "tenant-private-runtime",
      external_egress_requested: true,
      external_egress_allowed: false,
      egress_decision: "blocked_by_default",
      decision_reason: "External egress is blocked by tenant policy.",
      route_status: "watch",
      input_tokens: 900,
      output_tokens: 0,
      estimated_cost_eur: 0,
      latency_ms: 0,
      cost_center: "plant-operations",
      required_permissions: ["agents:read"],
      evidence_refs: [],
      audit_event_id: "33333333-3333-4333-8333-333333333333",
      observability_events: [],
    },
  ],
  budget_notes: [],
  observability_notes: [],
};

function auditEvent(
  index: number,
  overrides: Partial<ManufacturingAuditExplorer["events"][number]> = {},
): ManufacturingAuditExplorer["events"][number] {
  return {
    audit_event_id: `00000000-0000-4000-8000-00000000000${index}`,
    occurred_at: `2026-07-10T0${index}:15:00+02:00`,
    tenant_id: "tenant_fixture",
    actor_id: "plant-operations-owner-role",
    actor_type: "role",
    event_type: "workflow.signal.recorded",
    category: "workflow",
    domain: "Operations",
    scope: "wf_supplier_delay_review",
    result: "recorded",
    severity: "ready",
    source: "Axis API",
    summary: "Persisted workflow signal.",
    permission_scope: "workflows:read",
    data_classification: "public-demo",
    related_workflow_id: "wf_supplier_delay_review",
    related_approval_id: null,
    related_agent_id: null,
    evidence_refs: [],
    payload_preview: {},
    ...overrides,
  };
}

export const auditEventsFixture: ManufacturingAuditExplorer = {
  tenant_id: "tenant_fixture",
  plant_name: "Fixture Works",
  scenario: "Plant Operations Cockpit",
  as_of: "2026-07-10T10:30:00+02:00",
  ledger_status: "ready",
  metrics: [],
  filter_options: {
    tenants: ["tenant_fixture"],
    event_types: ["workflow.signal.recorded"],
    scopes: ["wf_supplier_delay_review"],
    actors: ["plant-operations-owner-role"],
    categories: ["workflow"],
  },
  events: [
    auditEvent(1, {
      event_type: "approval.decision.recorded",
      category: "approval",
      severity: "ready",
    }),
    auditEvent(2, {
      event_type: "connector.evidence_invariants.read",
      category: "connector",
      actor_id: "connector-runtime",
      severity: "watch",
    }),
    auditEvent(3),
    auditEvent(4, { event_type: "agent.proposal.recorded", category: "agent" }),
  ],
  retention_notes: [],
};

export const approvalInboxFixture: ManufacturingApprovalInbox = {
  tenant_id: "tenant_fixture",
  plant_name: "Fixture Works",
  scenario: "Plant Operations Cockpit",
  as_of: "2026-07-10T09:00:00+02:00",
  queue_status: "action_required",
  policy_notes: [],
  approvals: [
    {
      approval_id: "appr_fixture_expedite",
      action: "Expedite supplier batch",
      risk_level: "high",
      status: "pending",
      requested_by: "agent_supply_fixture",
      owner_role: "plant-operations-owner",
      due: "Today 17:30",
      workflow_id: "wf_supplier_delay_review",
      domain: "Supply",
      summary: "Approve or reject a governed supply expedite.",
      evidence: ["Supplier confirmed capacity for the expedite window."],
      data_accessed: ["Supplier status"],
      risks: ["External shipment mutation"],
      alternatives: ["Adjust production schedule"],
      estimated_cost: "EUR 120",
      model_policy: "no-external-egress",
      required_permission: "approvals:supply:decide",
      audit_event_preview: {
        event: "approval.decision.recorded",
        actor_role: "plant-operations-owner",
        scope: "wf_supplier_delay_review",
        result: "pending",
      },
      decision_options: [
        {
          decision: "approve",
          label: "Approve & execute",
          consequence: "The expedite order is dispatched to the supplier.",
        },
        {
          decision: "reject",
          label: "Reject",
          consequence: "The current production plan stays unchanged.",
        },
      ],
    },
    {
      approval_id: "appr_fixture_quality",
      action: "Place quality hold",
      risk_level: "medium",
      status: "pending",
      requested_by: "agent_quality_fixture",
      owner_role: "quality-owner",
      due: "Today 18:00",
      workflow_id: "wf_quality_hold",
      domain: "Quality",
      summary: "Review quality hold evidence.",
      evidence: ["QMS deviation recorded on lot 42."],
      data_accessed: ["QMS deviation summary"],
      risks: ["Production delay"],
      alternatives: ["Escalate to quality review"],
      estimated_cost: "EUR 0",
      model_policy: "local-only",
      required_permission: "approvals:quality:decide",
      audit_event_preview: {
        event: "approval.decision.recorded",
        actor_role: "quality-owner",
        scope: "wf_quality_hold",
        result: "pending",
      },
      decision_options: [
        {
          decision: "approve",
          label: "Approve hold",
          consequence: "The batch is held for quality review.",
        },
        {
          decision: "reject",
          label: "Reject",
          consequence: "The batch is released to shipping.",
        },
      ],
    },
    {
      approval_id: "appr_fixture_maintenance",
      action: "Shift maintenance window",
      risk_level: "low",
      status: "pending",
      requested_by: "agent_maintenance_fixture",
      owner_role: "maintenance-owner",
      due: "Tomorrow 08:00",
      workflow_id: "wf_maintenance_window",
      domain: "Maintenance",
      summary: "Move the Press 4 maintenance window.",
      evidence: ["CMMS window conflict detected."],
      data_accessed: ["CMMS schedule"],
      risks: ["Deferred maintenance"],
      alternatives: ["Keep current window"],
      estimated_cost: "EUR 40",
      model_policy: "local-only",
      required_permission: "approvals:maintenance:decide",
      audit_event_preview: {
        event: "approval.decision.recorded",
        actor_role: "maintenance-owner",
        scope: "wf_maintenance_window",
        result: "pending",
      },
      decision_options: [
        {
          decision: "approve",
          label: "Approve shift",
          consequence: "The maintenance window moves to the proposed slot.",
        },
        {
          decision: "reject",
          label: "Reject",
          consequence: "The current maintenance window stays in place.",
        },
      ],
    },
    {
      approval_id: "appr_fixture_fourth",
      action: "Fourth queued approval",
      risk_level: "low",
      status: "pending",
      requested_by: "agent_supply_fixture",
      owner_role: "plant-operations-owner",
      due: "Tomorrow 12:00",
      workflow_id: "wf_fourth",
      domain: "Supply",
      summary: "Only the top three approvals surface on the overview.",
      evidence: ["Queued behind higher-priority approvals."],
      data_accessed: ["Supplier status"],
      risks: ["None"],
      alternatives: ["Wait"],
      estimated_cost: "EUR 0",
      model_policy: "local-only",
      required_permission: "approvals:supply:decide",
      audit_event_preview: {
        event: "approval.decision.recorded",
        actor_role: "plant-operations-owner",
        scope: "wf_fourth",
        result: "pending",
      },
      decision_options: [
        {
          decision: "approve",
          label: "Approve",
          consequence: "The queued action executes.",
        },
        {
          decision: "reject",
          label: "Reject",
          consequence: "The queued action is cancelled.",
        },
      ],
    },
  ],
};

export const policyRegistryFixture: PlatformPolicyRegistry = {
  tenant_id: "tenant_fixture",
  policy_count: 2,
  active_policy_count: 1,
  policies: [],
  policy_notes: [],
};

export const identitySessionFixture: IdentitySessionReadModel = {
  authenticated: false,
  mode: "public_demo",
  actor_id: null,
  tenant_id: null,
  scopes: [],
  expires_at: null,
  api_auth_required: true,
  enterprise_sso_ready: true,
  readiness_status: "watch",
  issuer: "https://idp.example/realms/axis",
  audience: "limes-axis-api",
  jwks_source: "configured",
  session_boundary: "http_only_cookie_verified_by_axis_api",
  capabilities: [],
  limitations: [],
  notes: [],
};
