"""Generate the HTTP operation/handler ownership map from OpenAPI and source declarations."""

from __future__ import annotations

import argparse
import ast
from collections import Counter
from pathlib import Path

from axis_api.main import create_app

HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options", "trace"}
REPO_ROOT = Path(__file__).resolve().parents[3]


def handler_owners(source_root: Path) -> dict[str, str]:
    owners: dict[str, str] = {}
    for path in sorted(source_root.rglob("*.py")):
        for node in ast.walk(ast.parse(path.read_text())):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            if not any(
                isinstance(decorator, ast.Call)
                and isinstance(decorator.func, ast.Attribute)
                and decorator.func.attr in HTTP_METHODS
                for decorator in node.decorator_list
            ):
                continue
            if node.name in owners:
                raise ValueError(f"Ambiguous HTTP handler name: {node.name}")
            owners[node.name] = str(path.relative_to(source_root))
    return owners


def domain_for(path: str) -> str:
    for prefix, domain in (
        ("/identity/", "identity"), ("/platform/models/", "models"),
        ("/platform/policies", "policies"), ("/platform/tenants", "tenants"),
        ("/data/", "data-assets"),
    ):
        if path.startswith(prefix):
            return domain
    for prefix in ("/operations", "/demo/manufacturing"):
        if path == prefix or path.startswith(prefix + "/"):
            resource = path.removeprefix(prefix).strip("/").split("/")[0]
            return {
                "connectors": "connectors", "actions": "actions", "action-runs": "actions",
                "agents": "agents", "agent-runs": "agents", "approvals": "approvals",
                "audit": "audit", "ontology": "ontology", "model-routing": "models",
                "workflows": "workflows", "simulation": "simulation",
            }.get(resource, "operations")
    return "system"


def inventory(openapi: dict, source_root: Path) -> list[dict[str, str | bool]]:
    owners = handler_owners(source_root)
    rows = []
    for path, operations in sorted(openapi["paths"].items()):
        for method, operation in sorted(operations.items()):
            if method not in HTTP_METHODS:
                continue
            operation_id = operation["operationId"]
            candidates = [name for name in owners if operation_id.startswith(name + "_")]
            if not candidates:
                raise ValueError(f"No declared handler for operation: {operation_id}")
            name = max(candidates, key=len)
            rows.append({
                "method": method.upper(), "path": path, "domain": domain_for(path),
                "handler": name, "owner": owners[name],
                "deprecated": operation.get("deprecated", False),
            })
    return rows


def render_inventory(openapi: dict, source_root: Path) -> str:
    rows = inventory(openapi, source_root)
    counts = Counter(row["domain"] for row in rows)
    lines = [
        "# API route inventory", "",
        "<!-- Generated by services/api/scripts/export_route_inventory.py; do not edit. -->", "",
        "This inventory covers every OpenAPI HTTP operation, including deprecated",
        "aliases. Framework documentation/static routes are outside this API contract.",
        "Handler ownership is derived from source declarations; domain labels are",
        "the extraction map, not a claim that every domain already has a router.",
        "See [route extraction](api-route-extraction.md) for boundaries and verification.", "",
        f"**{len(rows)} operations**, {sum(row['deprecated'] for row in rows)} deprecated aliases.",
        "", "| Domain | Operations |", "| --- | ---: |",
    ]
    lines.extend(f"| {domain} | {count} |" for domain, count in sorted(counts.items()))
    lines.extend([
        "", "| Method | Path | Handler | Owner | Deprecated |",
        "| --- | --- | --- | --- | --- |",
    ])
    for row in rows:
        owner = str(row["owner"])
        module = "axis_api." + owner.removesuffix(".py").replace("/", ".")
        lines.append(
            f"| {row['method']} | `{row['path']}` | `{row['handler']}` | "
            f"[{module}](../services/api/src/axis_api/{owner}) | "
            f"{'yes' if row['deprecated'] else 'no'} |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Regenerate the committed inventory.")
    args = parser.parse_args()
    rendered = render_inventory(create_app().openapi(), REPO_ROOT / "services/api/src/axis_api")
    output = REPO_ROOT / "docs/api-route-inventory.md"
    if args.write:
        output.write_text(rendered)
    elif not output.exists() or output.read_text() != rendered:
        print("Route inventory is stale; run make route-inventory")
        return 1
    print("API route inventory OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
