"""Generate the API environment reference from declared defaults, never live settings."""

import argparse
import json
from pathlib import Path

from pydantic_settings import BaseSettings

from axis_api.config import Settings

REFERENCE = Path(__file__).resolve().parents[3] / "docs" / "configuration-reference.md"


def render_reference() -> str:
    lines = [
        "# API configuration reference",
        "",
        "Generated by `make settings-reference`; check with `make settings-reference-check`.",
        "Do not edit the tables by hand. Values come from field declarations, never the",
        "operator's environment or `.env`. Credential-bearing defaults are redacted.",
        "",
        "The API loads all capabilities once through `axis_api.config.Settings`.",
        "Python field names and `AXIS_*` aliases remain flat; there are no nested env keys.",
        "Precedence: constructor arguments, process environment, package-local `.env`,",
        "file secrets, then defaults. Unknown keys are ignored. Lists use JSON arrays.",
        "The root Make commands load the selected root env file as described in",
        "[development](development.md). This reference covers the API facade; the worker",
        "and SDK retain their own configuration and must be configured separately.",
        "",
        "See [configuration validation](configuration.md) for production combinations,",
        "ownership and compatibility evidence, and [deployment](deployment.md) for",
        "operational profiles and secret injection.",
    ]
    schema = Settings.model_json_schema()["properties"]
    for capability in Settings.__bases__:
        if capability is BaseSettings:
            continue
        lines += [
            "",
            f"## {capability.__name__.removesuffix('Settings')}",
            "",
            "| Environment variable | Python field | Type | Default | Constraints |",
            "| --- | --- | --- | --- | --- |",
        ]
        for name, field in capability.model_fields.items():
            definition = schema[field.alias]
            variants = definition.get("anyOf", [definition])
            types = " / ".join(item.get("type", "unknown") for item in variants)
            default = field.get_default(call_default_factory=True)
            if default is not None and (
                name.endswith(("_dsn", "_password", "_secret", "_key")) or name == "redis_url"
            ):
                default = "<redacted>"
            constraints = "; ".join(
                f"{key}: {value}"
                for item in variants
                for key, value in item.items()
                if key in {"minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum", "pattern"}
            ).replace("|", "&#124;")
            encoded_default = json.dumps(default).replace("|", "&#124;")
            lines.append(
                f"| `{field.alias}` | `{name}` | {types} | `{encoded_default}` | {constraints} |"
            )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Fail if the committed reference drifted"
    )
    args = parser.parse_args()
    content = render_reference()
    if args.check:
        if not REFERENCE.exists() or REFERENCE.read_text(encoding="utf-8") != content:
            parser.exit(1, "Configuration reference is stale; run make settings-reference.\n")
    else:
        REFERENCE.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
